config/routes.php
<?php

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;
use Cake\Core\Configure;

Router::scope('/', function ($routes) {
    $routes->extensions(['json', 'xml', 'html']);
    $routes->resources('/login');
});

Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
	
	$pages_name = Configure::read('pages_name');
    //$routes->extensions(['json']);
    //$routes->resources('Users');
    $routes->connect('/', ['lang'=>'/:lang', 'controller' => 'Pages', 'action' => 'display', 'home'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']);
    
    $routes->connect('/delphoto', ['lang'=>'/:lang', 'controller' => 'Companies', 'action' => 'delphoto'], ['routeClass' => 'ADmad/I18n.I18nRoute']);
    
    $routes->connect('/sharecounter', ['lang'=>'/:lang', 'controller' => 'Companies', 'action' => 'sharecounter'], ['routeClass' => 'ADmad/I18n.I18nRoute']);
    
	$routes->connect('/pages/*', ['lang'=>'/:lang', 'controller' => 'Pages', 'action' => 'display'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']);
    
	$routes->connect('/login', ['lang'=>'/:lang', 'controller' => 'Users', 'action' => 'login'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']);
	
	$routes->connect('/logout', ['lang'=>'/:lang', 'controller' => 'Users', 'action' => 'logout'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']);
	
	$routes->connect('/register', ['lang'=>'/:lang', 'controller' => 'Users', 'action' => 'register'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']);
    
	$routes->connect('/getpassword', ['lang'=>'/:lang', 'controller' => 'Users', 'action' => 'getpassword'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']);
	
	$routes->connect('/dashboard', ['lang'=>'/:lang', 'controller' => 'Users', 'action' => 'dashboard'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']);
	
	$routes->connect('/myaccount', ['lang'=>'/:lang', 'controller' => 'Users', 'action' => 'edit' ],
        ['routeClass' => 'ADmad/I18n.I18nRoute']);
	
	$routes->connect('/mycompany', ['lang'=>'/:lang', 'controller' => 'Companies', 'action' => 'edit' ], ['routeClass' => 'ADmad/I18n.I18nRoute']);
	
	$routes->connect('/packages', ['lang'=>'/:lang', 'controller' => 'Users', 'action' => 'packages' ], ['routeClass' => 'ADmad/I18n.I18nRoute']);
	
	
	
	
	$routes->connect('/'.$pages_name[1].'/:slug', ['lang'=>'/:lang', 'controller' => 'Requests', 'action' => 'view'], 
		['routeClass' => 'ADmad/I18n.I18nRoute' , 'pass'=>['slug'] ]);
	
	$routes->connect('/'.$pages_name[1], ['lang'=>'/:lang', 'controller' => 'Requests', 'action' => 'index'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']);
		
	$routes->connect('/'.$pages_name[0].'/:slug', ['lang'=>'/:lang', 'controller' => 'Companies', 'action' => 'view'], 
		['routeClass' => 'ADmad/I18n.I18nRoute',  'pass'=>['slug'] ]);
		
	$routes->connect('/'.$pages_name[0], ['lang'=>'/:lang', 'controller' => 'Companies', 'action' => 'index'], ['routeClass' => 'ADmad/I18n.I18nRoute']);

		
		
		
	$routes->connect('/companies/add', ['lang'=>'/:lang', 'controller' => 'Companies', 'action' => 'add'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']);
	
	$routes->connect('/articles', ['lang'=>'/:lang', 'controller' => 'Articles', 'action' => 'index'], 
		['routeClass' => 'ADmad/I18n.I18nRoute' ]);
	
	$routes->connect('/articles/:slug', ['lang'=>'/:lang', 'controller' => 'Articles', 'action' => 'view'], 
		['pass'=>['slug'], 'routeClass' => 'ADmad/I18n.I18nRoute' ]);
	
	$routes->connect('/requests/mylist', ['lang'=>'/:lang', 'controller' => 'Requests', 'action' => 'mylist'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']);
	
	$routes->connect('/requests/edit/:id', ['lang'=>'/:lang', 'controller' => 'Requests', 'action' => 'edit'],
        ['routeClass' => 'ADmad/I18n.I18nRoute' ,'pass' => ['id']]);
	
	$routes->connect('/requests/add', ['lang'=>'/:lang', 'controller' => 'Requests', 'action' => 'add'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']);
    
	$routes->connect('/users/activate/:id', ['lang'=>'/:lang', 'controller' => 'Users', 'action' => 'activate'], ['pass'=>['id'], 'routeClass' => 'ADmad/I18n.I18nRoute']);
	
	
	$routes->fallbacks('DashedRoute');
    //$routes->fallbacks(DashedRoute::class);
});

Router::prefix('admin', function ($routes) {
	$routes->connect('/', ['prefix' => 'admin', 'controller' => 'Users', 'action'=>'dashboard']);
	$routes->connect('/dashboard', ['prefix' => 'admin', 'controller' => 'Users', 'action'=>'dashboard']);
    
    $routes->connect('/delphoto', ['prefix' => 'admin', 'controller' => 'Companies', 'action' => 'delphoto']);
    $routes->fallbacks('InflectedRoute');
});
Plugin::routes();

src/Model/Entity/Request.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Request Entity
 *
 * @property int $id
 * @property int $user_id
 * @property int $category_id
 * @property int $subcategory_id
 * @property string $req_title
 * @property string $req_body
 * @property string $req_preferred_contact
 * @property string $req_activate
 * @property int $status
 *
 * @property \App\Model\Entity\User $user
 * @property \App\Model\Entity\Category $category
 * @property \App\Model\Entity\Subcategory $subcategory
 */
class Request extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];
}

src/Model/Table/ExportsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

class ExportsTable extends Table{

    public function initialize(array $config)   {
        parent::initialize($config);

        $this->setTable('exports');
        $this->setDisplayField('exp_name');
        $this->setPrimaryKey('id');

        $this->belongsTo('Companies', [
            'foreignKey' => 'company_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Categories', [
            'foreignKey' => 'category_id',
            'joinType' => 'INNER'
        ]);
        /*$this->belongsTo('Subcategories', [
            'foreignKey' => 'subcategory_id',
            'joinType' => 'INNER'
        ]);*/
        /*$this->belongsTo('Countries', [
            'foreignKey' => 'country_id',
            'joinType' => 'INNER'
        ]);*/
    }
    
    public function validationDefault(Validator $validator){
        $validator
            ->requirePresence('exp_name', 'create')
            ->notEmpty('exp_name');

        $validator
            ->integer('exp_price')
            ->requirePresence('exp_price', 'create')
            ->notEmpty('exp_price');

        $validator
            ->integer('exp_phone')
            ->requirePresence('exp_phone', 'create')
            ->notEmpty('exp_phone');

        $validator
            ->requirePresence('exp_desc', 'create')
            ->notEmpty('exp_desc');

        /*$validator
            ->requirePresence('exp_photos', 'create')
            ->notEmpty('exp_photos');*/

        $validator
            ->requirePresence('seo_keywords', 'create')
            ->notEmpty('seo_keywords');

        $validator
            ->requirePresence('seo_desc', 'create')
            ->notEmpty('seo_desc');

        return $validator;
    }
    public function buildRules(RulesChecker $rules){
        $rules->add($rules->existsIn(['company_id'], 'Companies'));
        $rules->add($rules->existsIn(['category_id'], 'Categories'));
        //$rules->add($rules->existsIn(['subcategory_id'], 'Subcategories'));
        //$rules->add($rules->existsIn(['country_id'], 'Countries'));

        return $rules;
    }
}

src/Controller/Admin/RequestsController.php
<?php
namespace App\Controller\Admin;

use App\Controller\AppController;


class RequestsController extends AppController{

    public function index()    {
        $this->paginate = [
            'contain' => ['Users', 'Categories', 'Countries', 'SubCategories', 'Cities']
        ];
        $requests = $this->paginate($this->Requests);

        $this->set(compact('requests'));
        $this->set('_serialize', ['requests']);
    }

    public function view($id = null){
        $rec = $this->Requests->get($id);
        $this->set('rec', $rec);
        $this->set('_serialize', ['rec']);
    }

	
	public function add(){
		$request = $this->Requests->newEntity();
		
		if ($this->request->is('post')) {
			$request = $this->Requests->patchEntity($request, $this->request->getData());
			
				
			$request->user_id = $this->Auth->User('id');
			$request->slug = $this->Do->adrs($request->req_title);
			$request->status = 0;
			
			if($request['req_preferred_langs'] == ''){
				$request->errors('_req_preferred_langs', ['_required'=>__('error_empty')]);
			}else{
                $request->req_preferred_langs = implode(',', $this->request->getData('req_preferred_langs'));
            }
			if($request['req_preferred_contacts'] == ''){
				$request->errors('_req_preferred_contacts', ['_required'=>__('error_empty')]);
			}else{
			     $request->req_preferred_contacts = implode(',', $this->request->getData('req_preferred_contacts'));
            }
			
			// upload photos
			for($i=0; $i<count($_FILES); $i++){
				$img='';
				if(!empty($_FILES['photo_'.$i]['name'])){
					$img = $_FILES['photo_'.$i];
					$thumb_params = array(
						array('doThumb'=>true, 'w'=>800, 'h'=>800, 'dst'=>'middle'),
						array('doThumb'=>true, 'w'=>300, 'h'=>300, 'dst'=>'thumb')
						);
					$this->Images->uploader('img/requests_photos', $img, null, $thumb_params);
				}
			}
			
			if(!empty($this->Images->photosname)){
				$request->req_photos = implode('|',$this->Images->photosname);
			}
			
            if ($newRec = $this->Requests->save($request)) {
                $this->Flash->success(__('save-success'));
                $this->Do->adder([
                    'user_id'=>0,
                    'assignedby_id'=>$this->Auth->User('id'),
                    'assign_target'=>'Requests, '.$newRec->id,
                    'assign_title'=>'New from admin',
                    'assign_notes'=>null,
                    'stat_created'=>date("Y-m-d H:i:s"),
                    'stat_delivered'=>null,
                    'status'=>0,
                ], 'Assignments');
                return $this->redirect('/requests/edit/'.$newRec->id);
            }
            $this->Flash->error(__('save-fail'));
        }
        $categories = $this->Requests->Categories->find('list', ['conditions' => ['parent_id'=>4]]);

		$cities = $this->Do->lcl( 
			$this->loadModel('Categories')->find('list')
				->where( ['parent_id'=>$request->country_id] )
				->orWhere( ['id'=>$request->country_id] )
		);
		
        $this->set(compact('request', 'categories'));
        $this->set('_serialize', ['request', 'cities']);
    }
	
    public function edit($id = null){
        $request = $this->Requests->get($id, [
            'contain' => []
        ]);
        $request->req_preferred_langs = explode(",", $request->req_preferred_langs);
        $request->req_preferred_contacts = explode(",", $request->req_preferred_contacts);
		
        if ($this->request->is(['patch', 'post', 'put'])) {
            $request = $this->Requests->patchEntity($request, $this->request->getData());
            
			if($this->request->getData('req_preferred_langs') == ''){
				$request->errors('req_preferred_langs', ['_required'=>__('error_empty')]);
			}else{
                $request->req_preferred_langs = implode(',', $this->request->getData('req_preferred_langs'));
            }
			if($this->request->getData('req_preferred_contacts') == ''){
				$request->errors('req_preferred_contacts', ['_required'=>__('error_empty')]);
			}else{
                $request->req_preferred_contacts = implode(',',  $this->request->getData('req_preferred_contacts'));
            }
			
            
			// upload photos
			for($i=0; $i<count($_FILES); $i++){
				$img='';
				if(!empty($_FILES['req_photos_'.$i]['name'])){
					$img = $_FILES['req_photos_'.$i];
					$thumb_params = array(
						array('doThumb'=>true, 'w'=>800, 'h'=>800, 'dst'=>'middle'),
						array('doThumb'=>true, 'w'=>300, 'h'=>300, 'dst'=>'thumb')
						);
					$this->Images->uploader('img/requests_photos', $img, null, $thumb_params);
				}
			}
			if(!empty($this->Images->photosname)){
                $all = array_filter(array_merge([$request->req_photos], $this->Images->photosname));
				$request->req_photos = implode('|',$all);
			}
            
            if ($this->Requests->save($request)) {
                $this->Flash->success(__('save-success'));

                return $this->redirect($this->referer());
            }
            $this->Flash->error(__('save-fail'));
        }
        $categories = $this->Requests->Categories->find('list', ['conditions' => ['parent_id'=>4]]);
        $subcategories = $this->Requests->Categories->find('list', ['conditions' => ['parent_id'=>$request->category_id]]);
		$cities = $this->Do->lcl( 
			$this->Requests->Categories->find('list')
				->where( ['parent_id'=>$request->country_id] )
				->orWhere( ['id'=>$request->country_id] )
		);
			
        $this->set(compact('request', 'categories', 'subcategories', 'countries', 'cities'));
        $this->set('_serialize', ['request']);
    }
    public function delete($id = null){
        $this->request->allowMethod(['post', 'delete']);
        $request = $this->Requests->get($id);
        if ($this->Requests->delete($request)) {
            $this->Flash->success(__('delete-success'));
        } else {
            $this->Flash->error(__('delete-fail'));
        }

        return $this->redirect(['action' => 'index']);
    }
	
	public function delphoto(){
		$this->autoRender = false;
		$request = $this->Requests->get( $_GET['id'] );
		$dt['id'] = $request->id;
		$dt[ $_GET['field'] ] = $this->Do->delItm( [$_GET['photo']], $request[$_GET['field']], 'img/request_photos' );
		$res = $this->Do->adder($dt, 'Requests');
		if( $res  ){
        	$this->Flash->success(__('save-success'));
         	return $this->redirect(['action' => 'edit', $request->id]);
		}
	}
	
	public function disable($id = null){
		
        $this->request->allowMethod(['post', 'delete']);
        $record = $this->Requests->get($id);
		$record->status == 1 ? $enbled = 0 : $enbled = 1;
		$record->id = $id;
		$record->status = $enbled;
        if ($this->Requests->save($record)){
            $this->Flash->success(__('disable-success').' '.$enbled);
        } else {
            $this->Flash->error(__('disable-fail'));
        }
        return $this->redirect($this->referer());
    }
}

src/Template/Admin/Requests/add.ctp
<div class="white_bg_block ">
	<div class="row ">
		
		<!-- body -->
		<div class="col-xs-12  ">
			<h1>
				<?php echo __('add_request')?>
			</h1>
			<div class="from-list-lt row">
				<div class="col-md-12">
					<div class="col-sm-12" >
						<?php echo  $this->Form->create($request, 
							['enctype'=>'multipart/form-data',  
							'class'=>'form-float form-alt', 'novalidate' => true]) ?>
						<div class="row">
                            
							<div class="form-group col-md-6 col-xs-12">
								<?php echo $this->Form->input('language_id', 
									['type' => 'select', "chk"=>"isSelected", 
									'options' => $this->Do->lcl( $this->Do->get('lang') ), 'empty'=>__('language_id'), 
									'label'=>__('language_id'), 
									'class'=>'form-control'])?>
							</div>
                            
							<div class="form-group col-md-6">
								<?php echo $this->Form->input('req_title', 
									['type'=>'text', 'label'=>__('req_title'), 
									'placeholder'=>__('req_title_desc'), "chk"=>"isEmpty", 
									'class'=>'form-control'])?>
							</div>
							<div class="form-group col-md-12">
								<?php echo $this->Form->input('req_desc', 
									['type'=>'textarea', 'label'=>__('req_body'), 
									'placeholder'=>__('req_body_desc'), "chk"=>"isParagraph", 
									'class'=>'form-control'])?>
							</div>
							<div class="form-group col-md-6 col-xs-12">
								<?php echo $this->Form->input('category_id', 
									['onClick'=>'getSubCat(0, "subcategory-id")', "chk"=>"isSelectEmpty",
									'onChange'=>'getSubCat(this, "subcategory-id")', 'type' => 'select', 
									'options' => @$categories, 'empty' => __('f_category'), 'label'=>__('category_id'), 
									'class'=>'form-control'])?>
							</div>
							<div class="form-group col-md-6 col-xs-12">
								<?php echo $this->Form->input('subcategory_id', 
									['type'=>'select', 'label'=>__('subcategory_id'), "chk"=>"isSelectEmpty", 
									'class'=>'form-control', 'options'=>@$subcategories,
									'empty' => __('f_subcategory')])?>
							  </div>
							
							<div class="form-group col-md-6 col-xs-12">
								<?php echo $this->Form->input('country_id', [
									'onClick'=>'getSubCat(0, "city-id", this)', "chk"=>"isSelectEmpty",
									'onChange'=>'getSubCat(this, "city-id", this)', 'type' => 'select', 
									'options' => @$countries, 'empty' => __('f_country'), 'label'=>__('f_country'), 
									'class'=>'form-control'])?>
							</div>
							<div class="form-group col-md-6 col-xs-12">
								<?php echo $this->Form->input('city_id', [
									'type'=>'select', 'label'=>__('city_id'), "chk"=>"isSelectEmpty", 
									'class'=>'form-control', 'options'=>@$cities,
									'empty' => __('f_city')])?>
							</div>
							
                            
                            <div class="clearfix form-group col-xs-12">
                                <div>
                                    <label> <?=__('req_preferred_contacts');?> </label>
                                </div>
                                <div class="mychckbox_container">
                                    <?= $this->Form->select('req_preferred_contacts', 
                                        $this->Do->lcl( $this->Do->get('prefered_contacts') ),
                                             ['multiple'=>'checkbox',
                                              'label'=>['class'=>'mycheckbox gray'],
                                              'chk'=>'isEmpty']); ?>
                                </div>
                            </div>
                            
                            <div class="clearfix form-group col-xs-12">
                                <div>
                                    <label> <?=__('company_preferred_langs');?> </label>
                                </div>
                                <div class="mychckbox_container">
                                    <?= $this->Form->select('company_preferred_langs', 
                                        $this->Do->lcl( $this->Do->get('prefered_langs') ),
                                             ['multiple'=>'checkbox',
                                              'label'=>['class'=>'mycheckbox gray'],
                                              'chk'=>'isEmpty']); ?>
                                </div>
                            </div>
							
							<div class="form-group col-md-12 col-xs-12">
								<?php echo $this->Form->input('seo_desc', ["chk"=>"isEmpty", 
									'type'=>'text', 'label'=>__('seo_desc'), 
									'placeholder'=>__('seo_desc'), 'class'=>'form-control'])?>
							</div>
							
							<div class="form-group col-md-12 col-xs-12 ">
                                <?=$this->element("tagInput", ["name"=>"seo_keywords"]);?>
                            </div>
							
							<div class="clearfix form-group col-xs-12 ">
								<label><?=__('req_photos')?></label>
								<?php echo $this->element('uploadForm', ['name'=>'req_photos',
									"msg"=>"upload_req_photos_msg"]);?>
							</div>
							<div class="form-group col-md-12">
								<button class="btn btn-info" type="submit"><?php echo __('Submit')?></button>
							</div>
						</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

src/Template/Admin/Requests/index.ctp
<div>
    <h3>
		<?= __('Requests') ?>
    </h3>
    <div style="overflow-x: scroll;">
        <table class="table">
            <thead>
                <tr>
                    <th><?= $this->Paginator->sort('id', __('id')) ?></th>
                    <th><?= $this->Paginator->sort('req_title', __('req_title')) ?></th>
                    <th class="hideMob"><?= $this->Paginator->sort('subcategory_id', __('subcategory_id')) ?></th>
                    <th class="hideMob"><?= $this->Paginator->sort('stat_views', __('stat_views')) ?></th>
                    <th class="hideMob"><?= $this->Paginator->sort('stat_shares', __('stat_shares')) ?></th>
                    <th class="hideMob"><?= $this->Paginator->sort('status', __('status')) ?></th>
                    <th class="actions"><?= __('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($requests as $request): ?>
                <tr>
                    <td><?= $this->Number->format($request->id) ?></td>
                    <td><?= h($request->req_title) ?></td>
                    <td class="hideMob"><?= $request->has('subcategory') ? 
						$this->Html->link($request->subcategory->category_name, 
							['controller' => 'Categories', 'action' => 'view', 
								$request->category->id]) : '' ?></td>
                    <td class="hideMob"><?= $this->Number->format($request->stat_views) ?></td>
                    <td class="hideMob"><?= $this->Number->format($request->stat_shares) ?></td>
                    <td class="hideMob"><?= $this->Number->format($request->status) ?></td>
                    <td class="actions">
                        <?php $request->status == 0 ? 
							$enable = '<i class="fa fa-check-circle" aria-hidden="true"></i>' : 
                            $enable = '<i class="fa fa-times-circle-o" aria-hidden="true"></i>';?>
                            
                        <?= $this->Html->link('<i class="fa fa-eye" aria-hidden="true"></i>', 
                            ['action' => 'view', $request->id], ['escape'=>false, 'class'=>'pageContent']) ?>
                            
                        <?= $this->Html->link('<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', 
                            ['action' => 'edit', $request->id], ['escape'=>false, 'class'=>'pageContent']) ?>
                            
                        <?= $this->Form->postLink($enable, ['action' => 'disable', $request->id], 
                            ['confirm' => __('change_status').' '.$request->id, 'escape'=>false]) ?>
                            
                        <?= $this->Form->postLink('<i class="fa fa-trash" aria-hidden="true"></i>', 
                            ['action' => 'delete', $request->id], 
							['confirm' => __('delete_record').' '.$request->id, 'escape'=>false]) ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    
</div>

<div class="paginator">
    <ul class="pagination">
        <?= $this->Paginator->prev('< ' . __('previous')) ?>
        <?= $this->Paginator->numbers() ?>
        <?= $this->Paginator->next(__('next') . ' >') ?>
    </ul>
    <p><?= $this->Paginator->counter() ?></p>
</div>

src/Template/Admin/Requests/mylist.ctp
<div id="vfx-product-inner-item">
	<div class="container">
		<div class="row">
			
			
			
			
			
			
			
			
			
			<!-- LIST -->
			<div class="col-md-9 col-sm-8 col-xs-12 nopadding">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="sorts-by-results">
						<div class="col-md-6 col-sm-6 col-xs-6">
							<span class="result-item-view">
								<?=__('query_result')?> <span class="yellow"><?=count($requests)?></span>
							</span>
						</div>
						<div class="col-md-6 col-sm-6 col-xs-6">
								<?php 
									$urlvars = $this->Do->appendURL('', 'array');
									if(!empty($urlvars[0])){
										foreach($urlvars as $itm){
											$itm_arr = explode('=',$itm);
											echo '
											<span class="tag_remove pull-left">'.
												__($itm_arr[0]).'<a href="'.$this->Do->appendURL($itm, 'remove').'">
												 <i class="fa fa-times"></i></a> 
											</span>';
										}
									}
								?>
						</div>
						<!--<div class="col-md-6 col-sm-6 col-xs-6">
              <div class="disp-f-right">
                <div class="disp-style"><a href="listing_grid.html"><i class="fa fa-th"></i></a></div>
                <div class="disp-style active"><a href="listing_list.html"><i class="fa fa-th-list"></i></a></div>
              </div>
            </div>-->
					</div>
					<?php foreach ($requests as $request): ?>
					<div class="recent-listing-box-container-item list-view-item" style="direction:rtl;">
						<div class="col-md-4 nopadding feature-item-listing-item listing-item">
							<div class="recent-listing-box-image">
								<h1>
									<?=$request->category->category_name?>
								</h1>
								<?php $img = explode('|', $request->req_photos);?>
								<?=$this->Html->image('/img/requests_photos/thumb/'.$img[0]);?>
							</div>
							<div class="hover-overlay">
								<div class="hover-overlay-inner">
									<ul class="listing-links">
										<li>
											<?=$this->Html->link(
												'<i class="fa fa-pencil"></i> '.__('rec_edit'),
												['action'=>'edit', $request->id],['escape'=>false])?>
										</li>
									</ul>
								</div>
							</div>
						</div>
						<div class="col-md-8 nopadding">
							<div class="recent-listing-box-item">
								<div class="listing-boxes-text">
									<h3>
										<?=$this->Html->link(
											$request->req_title, 
											['action'=>'view', $request->slug])
										?>
									</h3>
									<p>
										<?=$request->req_desc?>
									</p>
								</div>
								<div class="recent-feature-item-rating">
									<h2><i class="fa fa-map-marker"></i> <?=$request->country->category_name?></h2>
									<span>
										<?=$request->category->category_name?>
									</span>
								</div>
							</div>
						</div>
					</div>
					<?php endforeach;?>
					<div class="vfx-person-block">
						<ul class="vfx-pagination">
							<?= $this->Paginator->prev('<i class="fa fa-angle-double-right" aria-hidden="true"></i>', ['escape'=>false]) ?>
							<?= $this->Paginator->numbers() ?>
							<?= $this->Paginator->next('<i class="fa fa-angle-double-left" aria-hidden="true"></i>', ['escape'=>false]) ?>
						</ul>
					</div>
				</div>
			</div>
			
			<?=$this->Element('user_sidebar')?>
		</div>
	</div>
</div>

src/Template/Admin/Requests/view.ctp
<?php
$fields = ['id', 'slug', 'user_id', 'category_id', 'subcategory_id', 'country_id', 'city_id', 'req_title', 'req_desc', 'req_photos', 'req_preferred_contacts', 'req_preferred_langs', 'seo_keywords', 'seo_desc', 'stat_created', 'stat_views', 'stat_shares', 'status'];
?>
<div class="view_page">
    <h3><?=__('show').' '.__($this->request->controller.'_rec').' '.h($rec->id) ?>
		<?=$this->element('actions_btns', ["rec"=>$rec]);?></h3>
    <table class="vertical-table">
    
    <?php foreach($fields as $field):?>
        <tr>
            <th><?= __($field) ?></th>
            <td><?= $rec->$field ?></td>
        </tr>
	<?php endforeach?>
    </table>
</div>
<br />
<div ><?=$this->element('actions_btns', ["rec"=>$rec]);?></div>
<br />